config/routes.rb
Casecreed::Application.routes.draw do

  resources :sms do
    member do
      put 'verify_phone'
      get 'send_verification_code_again'
    end

  end

  resources :vote_for_next_cities

  resources :slots, :only=>[:index, :show,:new] do
    member do
      get "disable"
      get "enable"
    end
  end

  resources :appointments
  resources :casecreedblog
  resources :available_timings

  resources :ratings

  resources :images

  get "pages/about_us"
  get "pages/presskit"
  get "pages/logo"
  get "pages/privacy_policy"
  get "pages/terms_of_use"
  get "pages/how_it_works"
  get "pages/logo"
  get "pages/homepage"

  resources :search_accounts, :only=>[:index,:create] do
    member do
      get "claim"
      post "request_sent"
    end

    collection do
      post "search"
      get "search"
      get 'pending_request'
      post 'authenticate_requests'
    end
  end

  resources :messages, :only=>[:new,:show,:index,:create]

  resources :lawyers, :only=>[:index, :show,:new,:create] do
    collection do
      post 'search'
      get 'search'
      put 'update_profile'
      get 'edit'
      get 'get_timings_one_lawyer'
    end

    member do
      get "images"
      get "clients"
    end
    resources :specialities, :only=>[:new,:destroy, :create]
  end

  resources :reviews
  resources :categories,:except=>[:show] do
    collection do
      post 'get_sub_categories'
    end
  end

  resources :users do
    collection do
      get 'account_activate'
      get 'pending_request'
      post 'authenticate_requests'
      get  'settings'
      get 'no_sms_updates'
      put 'update_password'
    end

    member do
      get "lawyers"
    end

  end

  resources :forgot_password,:only=>[:create, :new] do
    collection do
      get 'change_password'
      post 'update_password'
    end
  end

  match 'home' => 'sessions#home', :as => :home
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'user_sign_up'=>'users#new',:as=>:user_sign_up
  match 'lawyer_sign_up'=>'lawyers#new',:as=>:lawyer_sign_up
  match 'select_user_type' => 'pages#select_user_type', :as=>:select_user_type
  match 'sessions/create' => 'sessions#create'
  root :to => "sessions#home"

end

app/controllers/search_accounts_controller.rb
class SearchAccountsController < ApplicationController
  before_filter :restricted_area, :only=>[:pending_request,:authenticate_requests]
  before_filter :account_inactive_and_exists, :only=>[:claim,:request_sent]
  before_filter :visitor_only,:only=>[:claim,:search,:index,:request_sent]
  def claim
    @claim=Claim.new
  end

  def search
    if params[:search]!=""
      @lawyers = []
      @lawyers = User.inactive_lawyers_search(params[:search], params[:page])
      @pagination=0
    else
      @lawyers=User.inactive_lawyers(params[:page])
    end
    render :action=>"index"
  end

  def index
    @lawyers=User.inactive_lawyers(params[:page])
  end

  def request_sent
    @claim=Claim.new(params[:claim])
    @claim.user_id=@lawyer.id
    if @claim.save
      flash[:notice]="We got you request we will contact you soon."
      redirect_to search_accounts_path
    else
      render :action => "claim"
    end
  end

  def authenticate_requests
    if params[:commit]=='Approve'
      Claim.where(["id in (?)",params[:select]]).collect {
        |x|
        password=random_string
        x.user.email = x.email
        x.user.activation_code=Digest::MD5.hexdigest(Time.now.to_i.to_s)
        x.user.password=password
        x.user.password_confirmation=password
        x.user.save(false)
        x.user.send_claim_account_activation_mail(password)
        x.delete
      }
      flash[:notice]="The selected invitation(s) has been approved."
    else
      Claim.where(["id in (?)",params[:select]]).collect {|x| x.destroy}
      flash[:notice]="The selected invitation(s) has been declined."
    end
    redirect_to  pending_request_search_accounts_path
  end

  def pending_request
    @claims = Claim.paginate(:page => params[:page],:order => 'created_at DESC')
  end

  private

  def account_inactive_and_exists
    @lawyer = User.where(['id = ? and active = ? and activation_code IS NULL', params[:id], 0]).first
    unless @lawyer
      flash[:error]="You are not authorized for this action."
      redirect_to search_accounts_path
    end
  end

end

app/helpers/search_accounts_helper.rb
module SearchAccountsHelper
end

app/views/search_accounts/claim.html.erb
<div id="claim_show">
	<div class="subheading">Claim for this profile</div>
	<table id="lawyers">
		<tr>
			<th id="lawyer_heading">Name</th>
			<th>Firm Name</th>
			<th>Office Number</th>
		</tr>


		<tr>
			<td class="lawyer_info">
				<div class="table_img"><a href="#"><%= image_tag(@lawyer.avatar.url(:thumb)) %></a></div>
				<div class="add_info">
					<div style="height:68px;">
						<p class="lawyer_name"><a href="#"><%= @lawyer.full_name %></a></p>
						<p class="address">
							<%= @lawyer.lawyer_detail.address %>
						</p>
					</div>
				</div>
			</td>
			<td style="vertical-align: top;">	<%= @lawyer.lawyer_detail.firm_name %></td>
			<td style="vertical-align: top;">	<%= @lawyer.lawyer_detail.office_phone %></td>

		</tr>


	</table>


	<div id="forms">
		<p>
			Please provide some details that help us to identify that this belongs to you. We will contact you soon.
		</p>
		<div id="form_left">
			<%= form_for @claim , :as => :claim , :url => request_sent_search_account_path do |f| %>
			<% if @claim.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

				<ul>
					<% @claim.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<div class="field">
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>

			<div class="field">
				<%= f.label :phone %>
				<%= f.text_field :phone %>
			</div>

			<div class="field">
				<%= f.label :message %>
				<%= f.text_area :message %>
			</div>

			<div class="actions">
				<%= f.submit "Request for Claim" ,:class => "orange_really_big_button" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/search_accounts/index.html.erb
<div class='search_lawyers'>
	<div class="subheading">Enter your Name to Search your account</div>
	<% form_tag search_search_accounts_path do -%>
	<%= text_field_tag 'search', params[:search] %>
	<%= submit_tag "Search" , :class=> "orange_button"%>
	<% end -%>
</div>
<table id="lawyers">
	<tr>
		<th id="lawyer_heading">Search results</th>
		<th class="day">Firm name</th>
		<th class="day">Office number</th>
		<th class="day">Claim for this account</th>
	</tr>

	<% @lawyers.each_with_index do |lawyer, index| %>
	<tr>
		<td class="lawyer_info" style="width:200px;">
			<div class="map_marker">
				<%= pagination_index(params[:page], index) %>)
				&nbsp;
			</div>
			<div class="table_img"><%= link_to image_tag(lawyer.avatar.url(:thumb)), claim_search_account_path(lawyer) %></div>
			<div class="add_info">
				<div style="height:68px;">
					<p class="lawyer_name"><%= link_to lawyer.full_name, claim_search_account_path(lawyer) %></p>
					<p class="address">
						<%= lawyer.lawyer_detail.address unless lawyer.lawyer_detail.nil? %>
					</p>
				</div>
			</div>
		</td>
		<td class="day day_color">	<%= lawyer.lawyer_detail.firm_name unless lawyer.lawyer_detail.nil?%></td>
		<td style="text-align:center;">	<%= lawyer.lawyer_detail.office_phone unless lawyer.lawyer_detail.nil?%></td>
		<td class="day day_color" style="font-size:12px !important;"> <%= link_to "Claim for this profile", claim_search_account_path(lawyer) %> </td>
	</tr>
	<% end %>

</table>
<div>	<%= will_paginate @lawyers , { :params => { :search =>
	params[:search]}} %></div>

app/views/search_accounts/pending_request.html.erb
<h3>List of Pending Requests</h3>
<table class="admin_table" cellspacing=0 , cellpadding=0 , width= 100%>
	<tr>
		<th>Name</th>
		<th>Description</th> 
		<th>Contact</th> 
		<th>Email</th>  
		<th>Actions</th>
	</tr>
	<%= form_tag(authenticate_requests_search_accounts_path) do %>
	<% @claims.each do |claim| %>
	<tr class="even">
		<td><%= claim.user.full_name %></td>
		<td><%= claim.message %></td>
		<td><%= claim.email %></td>
		<td><%= claim.phone %></td>
		<td><%= check_box_tag 'select[]', claim.id %></td>
	</tr>
	<% end %>


	<tr>
		<td colspan=4 align="right">
			<%= submit_tag "Approve" %> 
		</td>
		<td>	
			<%= submit_tag "Reject" %>
		</td>
	</tr>	
	<% end %>
</table>    