config/routes.rb
Casecreed::Application.routes.draw do

  resources :sms do
    member do
      put 'verify_phone'
      get 'send_verification_code_again'
    end

  end

  resources :vote_for_next_cities

  resources :slots, :only=>[:index, :show,:new] do
    member do
      get "disable"
      get "enable"
    end
  end

  resources :appointments
  resources :casecreedblog
  resources :available_timings

  resources :ratings

  resources :images

  get "pages/about_us"
  get "pages/presskit"
  get "pages/logo"
  get "pages/privacy_policy"
  get "pages/terms_of_use"
  get "pages/how_it_works"
  get "pages/logo"
  get "pages/homepage"

  resources :search_accounts, :only=>[:index,:create] do
    member do
      get "claim"
      post "request_sent"
    end

    collection do
      post "search"
      get "search"
      get 'pending_request'
      post 'authenticate_requests'
    end
  end

  resources :messages, :only=>[:new,:show,:index,:create]

  resources :lawyers, :only=>[:index, :show,:new,:create] do
    collection do
      post 'search'
      get 'search'
      put 'update_profile'
      get 'edit'
      get 'get_timings_one_lawyer'
    end

    member do
      get "images"
      get "clients"
    end
    resources :specialities, :only=>[:new,:destroy, :create]
  end

  resources :reviews
  resources :categories,:except=>[:show] do
    collection do
      post 'get_sub_categories'
    end
  end

  resources :users do
    collection do
      get 'account_activate'
      get 'pending_request'
      post 'authenticate_requests'
      get  'settings'
      get 'no_sms_updates'
      put 'update_password'
    end

    member do
      get "lawyers"
    end

  end

  resources :forgot_password,:only=>[:create, :new] do
    collection do
      get 'change_password'
      post 'update_password'
    end
  end

  match 'home' => 'sessions#home', :as => :home
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'user_sign_up'=>'users#new',:as=>:user_sign_up
  match 'lawyer_sign_up'=>'lawyers#new',:as=>:lawyer_sign_up
  match 'select_user_type' => 'pages#select_user_type', :as=>:select_user_type
  match 'sessions/create' => 'sessions#create'
  root :to => "sessions#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar,   :styles => {:thumb=> "190x170#", :medium  => "250x250>",:large=>"400x400>" }, :default_url => '/images/anonymous_icon.png'
  has_many :claims
  has_many :reviews, :foreign_key => 'lawyer_id'
  has_one :lawyer_detail
  has_one :client_detail
  has_one :sm
  has_many :lawyer_categories, :foreign_key => 'lawyer_id'
  has_many :categories, :through => :lawyer_categories
  has_many :slots, :foreign_key => "lawyer_id"
  has_many :images, :foreign_key=>'lawyer_id'
  has_many :available_timings, :foreign_key=>'lawyer_id'
  has_many :appointments_with_lawyers, :class_name => 'Appointment', :foreign_key => 'user_id'  #for client
  has_many :appointments_with_clients, :class_name => 'Appointment', :foreign_key => 'lawyer_id'  #for ADVOCATES
  attr_accessor :old_password
  accepts_nested_attributes_for :lawyer_detail, :allow_destroy => true
  accepts_nested_attributes_for :client_detail, :allow_destroy => true
  attr_accessor :password, :terms,:remember_me, :profile, :phone_number, :phone_carrier
  attr_accessor :password_confirmation
  validates_confirmation_of :password , :unless => lambda{ |a| a.profile=='1' }
  validates_length_of :password, :within => 6..20, :unless => lambda{ |a| a.password.blank? }
  validates_uniqueness_of :email, :unless => lambda{ |a| a.email.blank? or !a.new_record?}
  validates_presence_of :email, :first_name, :last_name,:account_type
  validates_presence_of :phone_number,:phone_carrier,  :unless => lambda{ |a| a.profile=='1' }
  validates_presence_of :password,  :unless => lambda{ |a| a.profile=='1' }
  validates_numericality_of :phone_number, :unless => lambda{ |a| a.phone_number.blank? }
  validates_length_of :phone_number, :is => 10, :unless => lambda{ |a| a.phone_number.blank? }
  validates_format_of :email,
  :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
  :unless => lambda{ |a| a.email.blank? }
  validates_acceptance_of :terms, :message => "must be accepted"
  validate :select_carrier, :unless => lambda{ |a| a.phone_number.blank? }
  validates_length_of :password, :within => 6..20, :unless => lambda{ |a| a.password.blank? }
  after_create :send_activation_mail , :unless => lambda{ |a| a.account_type == 'admin' }
  after_create :send_mobile_activation_code, :unless => lambda{ |a| a.phone_number.nil? or a.phone_carrier.nil? or a.phone_carrier =="Select a Carrier" }
  before_create :generate_activation_code
  before_destroy :send_rejection_mail
  cattr_reader :per_page
  @@per_page = 12
  def select_carrier
    if self.phone_carrier.nil? or self.phone_carrier == "Select a Carrier"
      errors.add(:base,"Please select phone carrier")
    end
  end

  def send_mobile_activation_code
    @sm = Sm.new
    @sm.user_id = self.id
    @sm.carrier = self.phone_carrier
    @sm.phone_number = self.phone_number
    @sm.save
  end

  def self.active_lawyers(page_number)
    where(['account_type = ? and active = ?', "lawyer", 1]).paginate(:page => page_number,:order => 'created_at DESC')
  end

  def self.all_lawyers(page_number)
    where(['account_type = ? ', "lawyer"]).paginate(:page => page_number,:order => 'created_at DESC')
  end

  def self.inactive_lawyers(page_number)
    where(['account_type = ? and active = ?', "lawyer", 0]).paginate(:page => page_number,:per_page=>30, :order => 'created_at DESC')
  end

  def old_password_match
    expected_password = User.encrypted_password(old_password, self.salt)
    if self.hashed_password != expected_password
      errors.add(:base,"Old Password is invalid.")
      return false
    else
      return true
    end
  end

  def self.inactive_lawyers_search(search_string,page_number)
    names=search_string.split(' ')
    lawyers = []
    names.each do |n|
      lawyers << self.where('first_name LIKE ? OR last_name LIKE ? and active = ? and activation_code = ?', "#{n}", "#{n}",0,nil)
    end
    lawyers.flatten!.compact
    lawyers.uniq!
    lawyers.paginate(:page => page_number,:per_page=> 10)
  end

  def self.unapproved_advacate_sign_up(page_number)
    where(['account_type = ? and approved = ?', "lawyer", 0]).paginate(:page => page_number,:order => 'created_at DESC')
  end


  def self.all_lawyers_search(page_number,category,keyword)
    if !category.blank? and !keyword.blank?
      keywords=keyword.split(' ')
      lawyers = []
      keywords.each do |n|
        lawyers << Category.find(category).users.where(['(account_type = ?) and (zipcode = ? or first_name = ? or last_name = ? )', "lawyer", n,n,n]).uniq
      end
      lawyers.flatten!.compact
      lawyers.uniq!
      lawyers.paginate(:page => page_number,:order => 'created_at DESC')
    elsif category.blank? and !keyword.blank?
      keywords=keyword.split(' ')
      lawyers = []
      keywords.each do |n|
        lawyers << where(['(account_type = ? ) and (zipcode = ? or first_name = ? or last_name = ?)', "lawyer", n,n,n]).uniq
      end
      lawyers.flatten!.compact
      lawyers.uniq!
      lawyers.paginate(:page => page_number,:order => 'created_at DESC')
    elsif !category.blank? and keyword.blank?
      Category.find(category).users.where(['account_type = ? ', "lawyer"]).uniq.paginate(:page => page_number,:order => 'created_at DESC')

    else

      where(['account_type = ?  ', "lawyer"]).uniq.paginate(:page => page_number,:order => 'created_at DESC')
    end
  end

  def full_name
    [first_name,last_name].join(' ')
  end

  def self.authenticate(email, password)
    user = self.find(:first, :conditions =>['email = ? and active = ?', email, 1])
    if user
      expected_password = encrypted_password(password, user.salt)
      if user.hashed_password != expected_password
        user = nil
      end
    end
    user
  end


  def generate_activation_code
    self.activation_code = Digest::MD5.hexdigest(rand.to_s +  rand.to_s)
    if self.account_type == "user"
      self.approved = 1
    else
      self.approved = 0
    end
  end

  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end

  def send_activation_mail
    if account_type=="lawyer" and approved==0
      Notifier.account_create_request_mail(self).deliver
    else
      Notifier.account_activation_mail(self).deliver
    end
  end

  def send_claim_account_activation_mail(password)
    Notifier.send_claim_account_activation_mail(self,password).deliver
  end

  def send_rejection_mail
    Notifier.send_rejection_mail(self).deliver

  end

  def send_password_recovery_mail
    Notifier.password_recovery(self).deliver
  end

  def password
    @password
  end

  def create_new_salt
    self.salt = Digest::MD5.hexdigest(rand.to_s)
  end

  def self.encrypted_password(password, salt)
    string_to_hash = password + "wibble" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end

  def self.random_string
    #generate a random password consisting of strings and digits
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(10) { |i| newpass << chars[rand(chars.size-1)] }
    return newpass
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :restricted_area, :only=>[:pending_request,:authenticate_requests]
  before_filter :no_visitors, :only => [:update_password, :settings,:no_sms_updates]
  before_filter :only_client, :only =>[:edit, :update]
  before_filter :authorize, :only=>[:show]
  before_filter :no_logged_in, :only=> [:new,:create]
  skip_before_filter :client_must_verify_phone_number, :only=>[:settings]

  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    @user.build_client_detail if @user.client_detail.nil?
  end

  def create
    @user = User.new(params[:user])
    @user.phone_carrier = params[:mobile_carrier]
    @user.account_type="user"
    if @user.save

    else
      render :action => "new"
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to(@user, :notice => 'User was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def account_activate
    reset_session
    user=User.where(["activation_code = ? ", params[:act] ]).first
    unless user.nil?
      user.activation_code=nil
      user.active=1
      user.save(false)
      @activated=1
      Notifier.welcome_mail(user).deliver
    else
      @activated=0
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(users_url)
  end

  def pending_request
    @users = User.unapproved_advacate_sign_up(params[:page])
  end

  def authenticate_requests
    if params[:commit]=='Approve'
      User.where(["id in (?)",params[:select]]).collect {
        |x|
        x.approved=1
        x.save(false)
        x.send_activation_mail
      }
      flash[:notice]="The selected invitation(s) has been approved."
    else
      User.where(["id in (?)",params[:select]]).collect {|x| x.destroy}
      flash[:notice]="The selected invitation(s) has been declined."
    end
    redirect_to  pending_request_users_path
  end

  def lawyers
    @lawyers = Appointment.select('distinct(lawyer_id)').where(['user_id = ? ', session[:user_id]])
  end

  def settings
    if @user.sm.nil?
      @sm = Sm.new
    else
      @sm = @user.sm

    end
  end

  def update_password
    @user = User.find(session[:user_id])
    @user.old_password=params[:user][:old_password]
    if  @user.old_password_match and @user.update_attributes(params[:user])
      flash[:notice] = 'Password updated successfully.'
      redirect_to settings_users_path
    else
      render :action => "settings"
    end
  end

  def no_sms_updates
    @user.sms_number = nil
    @user.sms_carrier = nil
    @user.save(:validate=>false)
    flash[:notice]="You will not recieve sms notifications. You an enable it anytime"
    redirect_to settings_users_path(@user)
  end

  private
  def authorize
    begin
      @client = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "This record does not exist."
      redirect_to(home_url)
    end

    unless @client.active == 1 and @client.account_type =='user'
      flash[:error] = "This record does not exist."
      redirect_to(home_url)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_change_password.html.erb
<div class="subheading">Change Password</div>
<div id="forms">
	<%= form_for @user , :url=> update_password_users_path  do |f|  %>
		<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this password from being saved:</h2>  						<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<div class="field">
			<%= f.label :old_password, "Old Password" %>
			<%= f.password_field :old_password %>
		</div>
		<div class="field">
			<%= f.label :password, "New Password" %>
			<%= f.password_field :password %>
			<span class="hint">(Longer than 6 characters and not easy to guess)</span>
		</div>

		<div class="field">
			<%= f.label :password_confirmation, "Confirm New Password" %>
			<%= f.password_field :password_confirmation %>
			<span class="hint">(same as above)</span>
		</div>

		<div class="field">
			<%= f.submit 'Change Password' , :class=>"orange_really_big_button" %>
		</div>
		<% end %>
	</div>

app/views/users/_new_sms_number.html.erb
<div id="lawyer_show">
	<div class="subheading">SMS Updates</div>
<span style="color:blue;""><i>We do not share your information with third parties, and we respect your privacy. </i></span>
	<% unless @user.sms_number.nil? %>
	<p>Currently you are receiving updates on your <%=@user.sms_number%> number. <%= link_to "No sms update", no_sms_updates_users_path %></p>
	<% end %>
	<div id="forms">
	<%= form_for(@sm) do |f| %>
	<% if @sm.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@sm.errors.count, "error") %> prohibited this sm from being saved:</h2>
		<ul>
			<% @sm.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :phone_number %>
		<%= f.text_field :phone_number %>
		<span class="hint">Please enter your 10 digit phone number, e.g. 1234567890</span>
	</div>

	<div class="field">
		<%= f.label :carrier %>
		<%= carrier_select %>
	</div>


	<div class="actions">
		<%= f.submit "Get Verification Code" , :class=>"orange_really_big_button" %>
	</div>
	<% end %>
</div>
</div>

app/views/users/_sms_settings.html.erb
<%if @user.sm.nil? %>

	<%= render :partial => "users/new_sms_number" %>

	<% else %>

	<%= render :partial => "users/verification_code" %>

	<% end %>

app/views/users/_verification_code.html.erb
<div id="lawyer_show">
	<div class="subheading">SMS Updates</div>
	<p>Please enter your verification code you received on your <%= @sm.phone_number %> number. <%= link_to 'Send verification code again', send_verification_code_again_sm_path(@sm) %></p>
<span style="color:blue;""><i>We do not share your information with third parties, and we respect your privacy.</i> </span>
	<div id="forms">
	<%= form_for @sm, :url=> verify_phone_sm_path(@sm) do |f| %>
	<% if @sm.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@sm.errors.count, "error") %> prohibited this sm from being saved:</h2>
		<ul>
			<% @sm.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :verification_code %>
		<%= f.text_field :verification_code, :value => nil %>
		<span class="hint">Enter your 4 digit verfication code</span>
	</div>
	<div class="actions">
		<%= f.submit "Activate", :class=>"orange_big_button" %>
	</div>
	<% end %>
</div>
</div>

app/views/users/account_activate.html.erb
<% if @activated==1 %>
<div id="forms">
	<div class="subheading">Account Activated</div>
	Your account has been activated please <%= link_to 'login', login_path %>
</div>
<% else %>
<div id="forms">
	<div class="subheading">Invalid Link</div>
	Sorry the link is invalid.
</div>

<% end %>

app/views/users/create.html.erb
<div id="forms">
	<div class="subheading">Activate your account</div>
	Your account has been created. Please verify your email address.
</div>

app/views/users/edit.html.erb
<div id="forms">
	<div class="subheading">Editing user</div>

	<%= form_for @user , :html => { :multipart => true } do |f| %>
		<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="field">
			<%= f.label :first_name %>
			<%= f.text_field :first_name %>
		</div>

		<div class="field">
			<%= f.label :last_name %>
			<%= f.text_field :last_name %>
		</div>
		<%= f.fields_for :client_detail do |a_d| %>
		<div class="field">
			<%= a_d.label :address %>
			<%= a_d.text_field :address %>
		</div>
		<% end %>
		<div class="field">
			<%= f.label :city %>
			<%= f.text_field :city %>
		</div>
		<div class="field">
			<%= f.label :state %>
			<%= f.text_field :state %>
		</div>
		<div class="field">
			<%= f.label :zipcode %>
			<%= f.text_field :zipcode %>
		</div>

		<div class="field">
			<%= f.hidden_field :profile,:value=> 1 %>
		</div>
		<div class="field">
			<%= f.label :avatar, "Profile Image" %>
			<%= f.file_field :avatar %>
		</div>
		<div class="actions">
			<%= f.submit "Update Details" , :class => "orange_really_big_button" %>
		</div>
		<% end %>
	</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
	<tr>
		<th>First name</th>
		<th>Last name</th>
		<th>Sex</th>
		<th>Street</th>
		<th>City</th>
		<th>Zipcode</th>
		<th>State</th>
		<th>Salt</th>
		<th>Hashed password</th>
		<th>Account type</th>
		<th>Email</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @users.each do |user| %>
	<tr>
		<td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
		<td><%= user.sex %></td>
		<td><%= user.street %></td>
		<td><%= user.city %></td>
		<td><%= user.zipcode %></td>
		<td><%= user.state %></td>
		<td><%= user.salt %></td>
		<td><%= user.hashed_password %></td>
		<td><%= user.account_type %></td>
		<td><%= user.email %></td>
		<td><%= link_to 'Show', user %></td>
		<td><%= link_to 'Edit', edit_user_path(user) %></td>
		<td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
	<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/lawyers.html.erb
<div id="lawyer_show">
	<div class="subheading">My Lawyers List</div>
	<p>This is a list of all lawyers you have on Casecreed.</p>
	<table id="index_page">
		<tr>
			<th>Lawyer Name</th>
			<th>Profile</th>

		</tr>

		<% @lawyers.each do |x| %>
		<tr class="<%= cycle("even", "odd") -%>">
			<td><%= x.lawyer.full_name %></td>
			<td><%= link_to 'View Profile', lawyer_path(x.lawyer) %></td>
		</tr>
		<% end %>
	</table>

</div>

app/views/users/new.html.erb
<div id="forms">
	<div class="subheading">Create an Account </div>
	<p id="new_sign_up">
		If you already have an Account, you can sign in <%= link_to 'here', login_path %>.

		<br/>Required information for Casecreed account
		<div id="form_left">
			<%= form_for(@user) do |f| %>
			<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

				<ul>
					<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>

			<div class="field">
				<%= f.label :first_name %>
				<%= f.text_field :first_name %>
			</div>
			<div class="field">
				<%= f.label :last_name %>
				<%= f.text_field :last_name %>
			</div>
			<div class="field">
				<%= f.label :email %>
				<%= f.text_field :email %>
				<span class="hint">e.g. myname@example.com  </span>
			</div>
			<div class='field'>
				<%= f.label :password, 'Password' %>
				<%= f.password_field :password, :size => 20 %>
				<span class="hint">(Longer than 6 characters and not easy to guess)</span>
			</div>
			<div class='field'>
				<%= f.label :password_confirmation, 'Confirm Password' %>
				<%= f.password_field :password_confirmation, :size => 20 %>
				<span class="hint">(same as above)</span>
			</div>
			<div>
				<%= f.label :phone_number %>
				<%= f.text_field :phone_number %>
				<span class="hint">Please enter your 10 digit phone number, e.g. 1234567890</span>
<span class="hint" style="color:blue;"">We do not share your information with third parties, and we respect your privacy. </span>
			</div>
			<div class="field">
				<%= f.label :phone_carrier %>
				<%= carrier_select %>
			</div>
			<div class='field' id="terms_condition">
				<%= f.check_box :terms %>
				By clicking on 'Create my account' below you are agreeing to the <%= link_to "Terms of Service" , pages_terms_of_use_path %>  and the <%= link_to "Privacy Policy" , pages_privacy_policy_path %>.
			</div>


			<div class="actions">
				<%= f.submit "Create my account" ,:class=> "orange_really_big_button" %>
			</div>
			<% end %>
		</div>
		<div id="form_right">
			<h5>Benefits of CaseCreed?</h5>
			<p>Real time access to appointments around the clock, anywhere, anytime, no waiting for office to open.Sync appointments with email client and get sms follow ups.Check out the review and choose your lawyer, No phone tag or hold book your appointment and be done!</p>
		</div>
	</div>

app/views/users/pending_request.html.erb
<h3>List of Pending Requests</h3>
<table class="admin_table" cellspacing=0 , cellpadding=0 , width= 100%>
	<tr>
		<th>Name</th>
		<th>Email</th>  
		<th>Actions</th>
	</tr>
	<%= form_tag(authenticate_requests_users_path) do %>
	<% @users.each do |user| %>
	<tr class="even">
		<td><%= user.full_name %></td>
		<td><%= user.email %></td>
		<td><%= check_box_tag 'select[]', user.id %></td>
	</tr>
	<% end %>
	<tr>
		<td colspan=2 align="right">
			<%= submit_tag "Approve" %> 
		</td>
		<td>	
			<%= submit_tag "Reject" %>
		</td>
	</tr>	
	<% end %>
</table>    

<div>	<%= will_paginate @users  %></div>

app/views/users/settings.html.erb
<div id="lawyer_show">

<% unless session[:account_type]=="user" and @user.sms_number.nil? %>
	<%= render :partial => "users/change_password" %>
	<% end %>

</div>
<% unless @user.account_type=="admin" %>
	<%= render :partial => "users/sms_settings" %>
	<% end %>

app/views/users/show.html.erb
<div id="user_show">

	<br/>
	<div id="lawyer_show">
		<div id='top_show_block'>
			<div id="lawyer_img">
				<%= image_tag @client.avatar.url(:thumb) %>
				<br/>
				<% if @client.id == session[:user_id]%>
				<%= link_to "edit", edit_user_path(@client),:class=>"orange_button" %>
				<% end %>
			</div>

			<div id="lawyer_show_info">
				<div id="lawyer_name_show"><%= @client.full_name %></div>
				<div id="block_left">
					<div id="address_show" class="info_block">
						<p class="show_heading">Address:</p>
						<p>
							<%= @client.client_detail.address unless @client.client_detail.nil? %><br/>
							<%= @client.city %> - <%= @client.zipcode %><br/>
							<%= @client.state %>
						</p>
					</div>
				</div>
			</div>

		</div>

	</div>
</div>