config/routes.rb
Casecreed::Application.routes.draw do

  resources :sms do
    member do
      put 'verify_phone'
      get 'send_verification_code_again'
    end

  end

  resources :vote_for_next_cities

  resources :slots, :only=>[:index, :show,:new] do
    member do
      get "disable"
      get "enable"
    end
  end

  resources :appointments
  resources :casecreedblog
  resources :available_timings

  resources :ratings

  resources :images

  get "pages/about_us"
  get "pages/presskit"
  get "pages/logo"
  get "pages/privacy_policy"
  get "pages/terms_of_use"
  get "pages/how_it_works"
  get "pages/logo"
  get "pages/homepage"

  resources :search_accounts, :only=>[:index,:create] do
    member do
      get "claim"
      post "request_sent"
    end

    collection do
      post "search"
      get "search"
      get 'pending_request'
      post 'authenticate_requests'
    end
  end

  resources :messages, :only=>[:new,:show,:index,:create]

  resources :lawyers, :only=>[:index, :show,:new,:create] do
    collection do
      post 'search'
      get 'search'
      put 'update_profile'
      get 'edit'
      get 'get_timings_one_lawyer'
    end

    member do
      get "images"
      get "clients"
    end
    resources :specialities, :only=>[:new,:destroy, :create]
  end

  resources :reviews
  resources :categories,:except=>[:show] do
    collection do
      post 'get_sub_categories'
    end
  end

  resources :users do
    collection do
      get 'account_activate'
      get 'pending_request'
      post 'authenticate_requests'
      get  'settings'
      get 'no_sms_updates'
      put 'update_password'
    end

    member do
      get "lawyers"
    end

  end

  resources :forgot_password,:only=>[:create, :new] do
    collection do
      get 'change_password'
      post 'update_password'
    end
  end

  match 'home' => 'sessions#home', :as => :home
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'user_sign_up'=>'users#new',:as=>:user_sign_up
  match 'lawyer_sign_up'=>'lawyers#new',:as=>:lawyer_sign_up
  match 'select_user_type' => 'pages#select_user_type', :as=>:select_user_type
  match 'sessions/create' => 'sessions#create'
  root :to => "sessions#home"

end

app/models/available_timing.rb
class AvailableTiming < ActiveRecord::Base
  belongs_to :user, :foreign_key=>"lawyer_id"
  has_many :slots, :dependent => :destroy
  attr_accessor :option ,:date_from,:date_to,:days
  validates_presence_of :time_from,:time_to,:option
  validates_presence_of :date_to, :if => lambda{ |a| a.option!='1' and !option.nil?}
  validates_presence_of :date_on, :unless => lambda{ |a| option.nil?}
  validate :validate_time_to_and_time_from
  validate :weekdays_select, :if => lambda{ |a| a.option=='3' }
  validate :no_past_date
  after_create :create_slots
  validate :timings_for_a_day_is_unique, :unless => lambda{ |a| option.nil?}



  def timings_for_a_day_is_unique
    if option=='1'
      all_specfied_timings_for_this_day= AvailableTiming.where(['date_on = ? and lawyer_id = ?', date_on, lawyer_id])
      all_specfied_timings_for_this_day.each do |specified_timing|
        if specified_timing.time_from < time_from and specified_timing.time_to > time_from
          errors.add(:base,"Timings already specified")
        elsif specified_timing.time_from < time_to and specified_timing.time_to > time_to
          errors.add(:base,"Timings already specified")
        elsif specified_timing.time_from >= time_from and specified_timing.time_to <= time_to
          errors.add(:base,"Timings already specified")
        end
      end
    end

    if option=="2"
      temp_date_from = date_from.to_datetime()
      temp_date_to = date_to.to_datetime()
      while temp_date_from <= temp_date_to
        all_specfied_timings_for_this_day= AvailableTiming.where(['date_on = ? and lawyer_id = ?', date_on, lawyer_id])
        all_specfied_timings_for_this_day.each do |specified_timing|
          if specified_timing.time_from < time_from and specified_timing.time_to > time_from
            errors.add(:base,"Timings already specified for " + temp_date_from.strftime("%m/%d/%Y"))
          elsif specified_timing.time_from < time_to and specified_timing.time_to > time_to
            errors.add(:base,"Timings already specified for " + temp_date_from.strftime("%m/%d/%Y"))
          elsif specified_timing.time_from >= time_from and specified_timing.time_to <= time_to
            errors.add(:base,"Timings already specified for " + temp_date_from.strftime("%m/%d/%Y"))
          end
        end
        temp_date_from =temp_date_from.advance(:days => 1)
      end
    end


    if option=="3" and  !days.nil?
      temp_date_from = date_from.to_datetime()
      temp_date_to = date_to.to_datetime()
      while temp_date_from <= temp_date_to
        if days.include?(temp_date_from.strftime("%w"))
          all_specfied_timings_for_this_day= AvailableTiming.where(['date_on = ? and lawyer_id = ?', temp_date_from, lawyer_id ])
          all_specfied_timings_for_this_day.each do |specified_timing|
            if specified_timing.time_from < time_from and specified_timing.time_to > time_from
              errors.add(:base,"Timings already specified for " + temp_date_from.strftime("%m/%d/%Y"))
            elsif specified_timing.time_from < time_to and specified_timing.time_to > time_to
              errors.add(:base,"Timings already specified for " + temp_date_from.strftime("%m/%d/%Y"))
            elsif specified_timing.time_from >= time_from and specified_timing.time_to <= time_to
              errors.add(:base,"Timings already specified for " + temp_date_from.strftime("%m/%d/%Y"))
            end
          end
        end
        temp_date_from =temp_date_from.advance(:days => 1)
      end
    end

  end

  def validate_time_to_and_time_from
    if time_from > time_to or time_from == time_to
      errors.add(:base,"Timings are invalid")
    end
  end


  def no_past_date
    if !date_from.blank? and date_from.to_datetime() < Date.today
      errors.add(:date_from, " is invalid")
    end

    if !date_to.blank? and date_to.to_datetime() < Date.today and option!=1 and !option.nil?
      errors.add(:date_to, " is invalid")
    end
  end

  def weekdays_select
    if days.nil? or days.length == 0
      errors.add(:days, " is invalid")
    end
  end

  def create_slots
    temp_time_from = self.time_from
    temp_time_to = self.time_to
    while temp_time_from.advance(:minutes => 30) <= self.time_to
      slot = Slot.new
      slot.date_on = self.date_on
      slot.lawyer_id = self.lawyer_id
      slot.available_timing_id=self.id
      slot.start_time = temp_time_from
      slot.end_time =temp_time_from.advance(:minutes => 30)
      slot.save
      temp_time_to= temp_time_to.advance(:minutes => 30)
      temp_time_from = temp_time_from.advance(:minutes => 30)
    end


    if option == "2"
      temp_date_from = date_from.to_datetime()
      temp_date_from=temp_date_from.advance(:days => 1)
      temp_date_to = date_to.to_datetime()
      while temp_date_from <= temp_date_to
        available_timing = AvailableTiming.new
        available_timing.lawyer_id = self.lawyer_id
        available_timing.time_from = self.time_from
        available_timing.time_to = self.time_to
        available_timing.option = "1"
        available_timing.date_on =temp_date_from
        available_timing.save
        temp_date_from =temp_date_from.advance(:days => 1)
      end
    end

  end



end

app/controllers/available_timings_controller.rb
class AvailableTimingsController < ApplicationController

  before_filter :only_lawyers
  before_filter :authorize, :only=>[:show,:destroy]

  def index
    @available_timings = @user.available_timings.where('date_on >= ? ', Date.today - 7 ).paginate(:page => params[:page],:order => 'date_on DESC', :per_page=> 15)
  end

  def show
  end

  def new
    @available_timing = AvailableTiming.new
  end

  def create
    @available_timing = AvailableTiming.new(params[:available_timing])
    @available_timing.lawyer_id=session[:user_id]
    @available_timing.date_on=params[:available_timing][:date_from]
    if @available_timing.valid?
      if params[:available_timing][:option]=="3"
        temp_date_from =@available_timing.date_from.to_datetime()
        temp_date_to = @available_timing.date_to.to_datetime()
        while temp_date_from <= temp_date_to
          if @available_timing.days.include?(temp_date_from.strftime("%w"))
            available_timing = AvailableTiming.new
            available_timing.lawyer_id = session[:user_id]
            available_timing.time_from = @available_timing.time_from
            available_timing.time_to = @available_timing.time_to
            available_timing.option = "1"
            available_timing.date_on =temp_date_from
            available_timing.save
          end
          temp_date_from =temp_date_from.advance(:days => 1)
        end
      else
        @available_timing.save
      end
      redirect_to(@available_timing, :notice => 'Available timing was successfully created.')
    else
      render :action => "new"
    end
  end


  def destroy
    @available_timing.destroy
    flash[:notice] = "Available timing destroyed successfully."
    redirect_to(available_timings_url)
  end

  private


  def authorize
    begin
      @available_timing = AvailableTiming.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "This record does not exist."
      redirect_to(available_timings_url)
    else
      unless  @available_timing.lawyer_id == session[:user_id]
        flash[:error] = "You are not authorized for this action."
        redirect_to(available_timings_url)
      end
    end
  end
end

app/helpers/available_timings_helper.rb
module AvailableTimingsHelper
end

app/views/available_timings/index.html.erb
<div id="lawyer_show">
	<div class="subheading">Listing Available Timings</div>
	<p>Add your availabity so that clients can book appointment with you online. </p>
	<br/>
	<%= link_to 'New Available Timing', new_available_timing_path ,:class => "orange_really_big_button" %>
	<table id="index_page">
		<tr>
			<th>Date On</th>
			<th>Time From</th>
			<th>Time To</th>
			<th></th>
			<th></th>
		</tr>

		<% @available_timings.each do |available_timing| %>
		<tr class="<%= cycle("even", "odd") -%>">
			<td><%= available_timing.date_on.strftime("%m/%d/%Y") %></td>
			<td><%= available_timing.time_from.strftime("%I.%M %p")  %></td>
			<td><%= available_timing.time_to.strftime("%I.%M %p")  %></td>
			<td><%= link_to 'Show', available_timing %></td>
			<td><%= link_to 'Delete', available_timing, :confirm => 'All you appointments will be canceled. Do you really want to delete?', :method => :delete %></td>
		</tr>
		<% end %>
	</table>

	<br />
	<div>	<%= will_paginate @available_timings  %></div>

</div>

app/views/available_timings/new.html.erb
<div id="forms">
	<div class="subheading">New Available Timing</div>
	<div id="form_left">
		<%= form_for(@available_timing) do |f| %>
		<% if @available_timing.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@available_timing.errors.count, "error") %> prohibited this available_timing from being saved:</h2>

			<ul>
				<% @available_timing.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<div class="field" id="available_timing_radio" style="overflow:hidden">
			<span style="float:left;"><%= radio_button("available_timing", "option", "1") %></span><span style="float:left;margin:0 10px 0 4px;"> For the Day</span>
			<span style="float:left;"><%= radio_button("available_timing", "option", "2") %></span> <span style="float:left;margin:0 10px 0 4px;">Daily</span>
			<span style="float:left;"><%= radio_button("available_timing", "option", "3") %></span> <span style="float:left;margin:0 10px 0 4px;">Weekly</span>
		</div>
		<div class="field">
			<%= f.label :date_from, "Date from" %>
			<%= f.text_field :date_from %>
		</div>

		<div class="field" id="date_to"  style=<%='display:none;' unless @available_timing.option == '2' or @available_timing.option=='3' %> >
			<%= f.label :date_to %>
			<%= f.text_field :date_to %>
		</div>
		<div class="field"  style='display:none;' >
			<%= label_tag "Number of Day" %>
			<%= text_field_tag 'number_of_days' %>
		</div>

		<div class="field" id="days" style=<%='display:none;' unless @available_timing.option=='3' %>>
			<%= label_tag "Days" %>
			<%= check_box_tag 'available_timing[days][]', "0" %>Sunday
			<%= check_box_tag 'available_timing[days][]', "1" %>Monday
			<%= check_box_tag 'available_timing[days][]', "2" %>Tuesday
			<%= check_box_tag 'available_timing[days][]', "3" %>Wednesday
			<%= check_box_tag 'available_timing[days][]', "4" %>Thrusday
			<%= check_box_tag 'available_timing[days][]', "5" %>Friday
			<%= check_box_tag 'available_timing[days][]', "6" %>Saturday
		</div>

		<div class="field">
			<%= f.label :time_from %>
			<%= f.time_select :time_from ,  :minute_step => 15, :twelve_hour => true %>
		</div>



		<div class="field">
			<%= f.label :time_to %>
			<%= f.time_select :time_to, :minute_step => 15 , :twelve_hour => true	 %>
		</div>
		<div class="actions">
			<%= f.submit  :class => "orange_really_a_big_button" %>
		</div>
		<% end %>
		<%= link_to 'Back', available_timings_path %>

	</div>
	<div id='form_right'>
		<h5>Specify Available Timings</h5>
		<p>You can add your availablity for one day, multiple days or particular days of week. Your time of availability will be divided into 30 minute slots for appointments with clients.</p>
	</div>
</div>

app/views/available_timings/show.html.erb
<div id="lawyer_show">

	<div class="subheading">Listing Available Timings On <%= @available_timing.date_on.strftime("%m/%d/%Y") %></div>
	<p>This is a list of all your available slots for the above date. Disabled slots will not be visible to clients. Status "0" indicates empty slot, "1" indicates booked slot.</p>
	<p>
		<b>From:</b>
		<%= @available_timing.time_from.strftime("%I %p") %>
	</p>

	<p>
		<b>To:</b>
		<%= @available_timing.time_to.strftime("%I %p") %>
	</p>


	<%= link_to 'Back', available_timings_path %>

	<br/>

	<table id="index_page">
		<tr>
			<th>Time From</th>
			<th>Time To</th>
			<th>Status</th>
			<th></th>
		</tr>

		<% @available_timing.slots.each do |slot| %>
		<tr class="<%= cycle("even", "odd") -%>">
			<td><%= slot.start_time.strftime("%I.%M %p")  %></td>
			<td><%= slot.end_time.strftime("%I.%M %p")  %></td>
			<td><%= slot.status %></td>
			<% if slot.active == 1 %>
				<% if slot.status == 1 %>
				<td><%= link_to 'Disable', disable_slot_path(slot), :confirm => 'Disabling the slot will hide this from your availabel timings and will cancel your appointment. Are you sure?' %></td>
				<% else %>
				<td><%= link_to 'Disable', disable_slot_path(slot), :confirm => 'Are you sure?' %></td>
				<% end %>
				<% else %>
				<td><%= link_to 'Enable', enable_slot_path(slot), :confirm => 'Are you sure?' %></td>
				<% end %>
			</tr>
			<% end %>
		</table>
	</div>